[package]
name = "ingest-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
document-vlm-runtime = { path = "../document-vlm-runtime" }
domain-model = { path = "../domain-model" }
event-bus = { path = "../event-bus" }
observability = { path = "../observability" }
platform-api = { path = "../platform-api" }
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
sqlx.workspace = true
storage = { path = "../storage" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
workflow-definitions = { path = "../workflow-definitions" }
workflow-engine = { path = "../workflow-engine" }
zip.workspace = true

[dev-dependencies]
test-fixtures = { path = "../test-fixtures" }
